spring.application.name=backend_viaticos

# ===================================================================
# 1. CONFIGURACIÓN DE SERVIDOR
# ===================================================================
server.port=8080
server.servlet.context-path=/api

# ===================================================================
# 2. CONEXIÓN A ORACLE AUTONOMOUS DATABASE (NUBE)
# ===================================================================
# Estas 3 variables se sobrescribirán en el Container Instance
spring.datasource.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=g12aa71a0638e28_dbviaticos_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=VIATICOS_USER
spring.datasource.password=Datum_App2026*

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# 3. SPRING CLOUD Y OCI
# ===================================================================
spring.cloud.function.definition=procesarGasto

# Variables de OCI (Se pueden sobrescribir en Docker)
oci.bucket.name=bucket-img_webp
oci.bucket.temp.name=bucket-Temp_img
oci.namespace=idfb49jm9xbb
oci.region=us-ashburn-1
app.compartmentId=ocid1.compartment.oc1..aaaaaaaao3u6k74czpxqyr7pfh2r6pmo7ta2repzyztkpdyqswa4dzg2pwrq

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

exchangerate.api.key=2ad1f47b9bc1cf0bcafbfbf2

# Variables de Autenticación (Se usan solo si las variables de entorno OCI_TENANCY_ID, etc. no están presentes)
oci.config.path=C:\\Users\\datum\\.oci\\config
oci.config.profile=DATUM_PROD